### ISSUE TITLE
InterceptGUI missing ?!

### ISSUE THREAD

**Issue by Superdrac** [DevilMental/CoCProxy#1]
Salut, j'ai regardé un peu ce que tu avais fait au niveau du proxy, je l'ai testé mais il manque le GUI, peux tu l'uploader ?

Merci !

**Comment by DevilMental** [comment]
Merci d'avoir regardé mon code ;)
Malheureusement le code sur GitHub n'est pas le code complet puisque celui que j'ai actuellement est bien plus avancé. L'interceipt GUI est une fenêtre avec les Packets reçus mais rien de spécial ;) si tu cherches à reproduire un proxy sur clash of clans renseigne toi sur ce forum : http://cocdevforum.ml/forum/ 
~ DevilMental

Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Superdrac <notifications@github.com> 
Date : 12/05/2015  20:10  (GMT+01:00) 
À : DevilMental/CoCProxy <CoCProxy@noreply.github.com> 
Objet : [CoCProxy] InterceptGUI missing ?! (#1) 

Salut, j'ai regardé un peu ce que tu avais fait au niveau du proxy, je l'ai testé mais il manque le GUI, peux tu l'uploader ?

Merci !

**Comment by Superdrac** [comment]
Merci à toi pour cette réponse rapide ! J'aimerais me lancer mais j'avoue avoir besoin de plus d'infos... Tu ne peux pas pusher le projet tel que tu l'a en local aujourd'hui ?

Après si il est possible qu'on discute autrement que sur github, je suis preneur !

**Comment by DevilMental** [comment]
Le projet que j'ai en local contient des informations confidentielles (telles que l'encryption et la decryption des packets) et c'est donc pour cette raison que je ne peux pas les divulguer. Mais si tu recherches plus d'information tu peux aller sur ce forum (où je me trouve) et poster un topic pour avoir peut être les informations que tu recherches http://cocdevforum.ml/forum
~ DevilMental


Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Superdrac <notifications@github.com> 
Date : 12/05/2015  20:54  (GMT+01:00) 
À : DevilMental/CoCProxy <CoCProxy@noreply.github.com> 
Cc : Alexandre de Angelis <devilmental@moneyquest.fr> 
Objet : Re: [CoCProxy] InterceptGUI missing ?! (#1) 

Merci à toi pour cette réponse rapide ! J'aimerais me lancer mais j'avoue avoir besoin de plus d'infos... Tu ne peux pas pusher le projet tel que tu l'a en local aujourd'hui ?

Après si il est possible qu'on discute autrement que sur github, je suis preneur !

**Comment by Superdrac** [comment]
Ok merci quand meme ! J'ai regardé un peu le forum mais il n'y a pas de solution "clefs en mains" si je puis dire.. Pour la décryption/encryption, tu a pourtant laissé les clés dans le fichier Crypt  ! 

Bref merci à toi !

**Comment by Superdrac** [comment]
http://ultrapowa.com/forum/viewtopic.php?f=2&t=985 Ta été dans la même situation en plus.

**Comment by DevilMental** [comment]
Il ne faut pas croire qu'une solution "clés en mains" tombera du ciel comme ça. Il faut bosser mon gars ;) J'ai trouvé toutes les informations en décompilant le jeu, et c'est pas comme si c'était open-source! 

Si tu n'es pas content fait le toi même mais comme la plupart te répondront, les systèmes de packets de clash of clans doivent faire preuve d'une extrême discretion ce qui est indiscutable.

Désolé
~ DevilMental

**Comment by Superdrac** [comment]
Tu n'as pas tord, mais ne me repproche pas de demander ça alors que tu l'a fais aussi :smiley: 

Je vais le faire de toute façon, ça aurais juste pris moins de temps si tu avais bien voulu partager tes sources, et j'aurais pu me consacrer au dev de l'outil que je vais faire autour. Sur ce, je pense que tu peux supprimer le repo (pour la discretion des paquets et les clés dispo dans Crypt.java), je t'ai ajouté sur facebook au passage.
